### ISSUE TITLE
Email verification doesn't work...

### ISSUE THREAD

**Issue by seanosh** [Automattic/vip-support#15]
For sites that I've been SQL importing, since `wp-cli` doesn't work and editing SQL dumps is about as fun as sliding down a razor blade into a pool of lemon juice, I've been adding the following file and just executing it on each site:

```
<?php
require('../../wp-load.php');
$user_id = wp_create_user('sysopsXX', 'password12345', 'sysops@automattic.com');
$user_id = wp_update_user( array( 'ID' => $user_id, 'role' => 'administrator' ) );
```

Shortly after the site is working, I receive an email:

```
Dear Automattician,

You need to verify your Automattic email address for your user on WooSlider (http://www.whatever.com). If you are expecting this, please click the link below to verify your email address:
http://www.whatever.com?vip_verify_code=X&vip_user_login=sysopsXX

If you have any questions, please contact the WordPress.com VIP Support Team.
```

Even if I click the link immediately after receiving the email, I'm still presented with the error message that the code is invalid or has already been used. 

[slack convo](https://a8c.slack.com/archives/vip-platform/p1444344668001397)

**Comment by scottsweb** [comment]
Closing as #38 fixed this. cc @simonwheatley
