### ISSUE TITLE
VIP Support Role lacks user level

### ISSUE THREAD

**Issue by kraftbj** [Automattic/vip-support#21]
Since the built-in role only has the "Read" cap, WP assigns it level_0 in the old deprecated way. This typically doesn't matter except wp_user_query still depends on the user role in the who=>author query.

Suggestion is to add specifically level_10 cap to https://github.com/Automattic/vipv2-support/blob/47553bbd53c8eb3ffb3613d8333a6c18a880315f/class-vip-support-role.php#L124 or at least add a native capability that would result in WP auto-assigning 10, since we want to mimic highest-level access.

Related core ticket: https://core.trac.wordpress.org/ticket/27060

**Comment by GaryJones** [comment]
Fixed with #37.
