### ISSUE TITLE
Support User creation on multisite fails

### ISSUE THREAD

**Issue by ryanmarkel** [Automattic/vip-support#35]
Running the support user creation steps fails when trying to do so for a multisite-enabled site. (Conjecture from @nickdaugherty.)

The error message from cli is:

```
Running module wp
Error: Site  not found.
```

**Comment by nickdaugherty** [comment]
We'll need to add the `--url` param when running the command on multisites (this will have to happen at the API level).

**Comment by joshbetz** [comment]
Going to close this as it's at the API level as Nick pointed out. We're still tracking it in the associated API issue.
