### ISSUE TITLE
All A11n users are moved into the VIP Support role on verifying their email

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/vip-support#40]
Users should only be moved into the VIP Support role if they are in the "VIP Support (inactive)" role, otherwise they should be left alone.

**Comment by ethitter** [comment]
We've largely circumvented the issue by relying on WP-CLI to create the users, which auto-verifies the email. This issue is largely confined to a8c properties hosted on Go, where non-VIP Automatticians are using their a8c email addresses. Related: p2-p6r3EZ-JF
