### ISSUE TITLE
Can't connect to JP

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/vip-support#80]
This filter prevents us from being able to connect accounts to JP: https://github.com/Automattic/vip-support/blob/master/class-vip-support-user.php#L176

Was added in https://github.com/Automattic/vip-support/commit/49eb8570b66b3e4f7fc9795637d21cf0e1bd47b7.

CC @davidsword

**Comment by mjangda** [comment]
@WPprodigy can you share a bit more details about why that filter blocks logins?

**Comment by WPprodigy** [comment]
Hummm, it's working now with the filter enabled 🤔.

I didn't spend too much time looking into this earlier, but I did replicate it twice so that's odd.

I'll close for now.
